package com.ayuu.instapong;
import android.app.*;import android.content.*;import android.graphics.*;import android.hardware.display.*;import android.media.*;import android.media.projection.*;import android.os.*;import java.nio.ByteBuffer;
public class ScreenCaptureService extends Service {
 public static final String EXTRA_RESULT_CODE="resultCode",EXTRA_DATA="data";private static final String CHANNEL="pong_bot";
 private MediaProjection projection;private VirtualDisplay display;private ImageReader reader;private HandlerThread thread;private Handler handler;private final PongDetector detector=new PongDetector();private float lastBallX=-1,lastBallY=-1,vx=0,vy=0,currentTouchX=-1;private long lastTs=0;
 @Override public void onCreate(){super.onCreate();createChannel();thread=new HandlerThread("pong-capture");thread.start();handler=new Handler(thread.getLooper());}
 @Override public int onStartCommand(Intent intent,int flags,int startId){int resultCode=intent.getIntExtra(EXTRA_RESULT_CODE,0);Intent data=intent.getParcelableExtra(EXTRA_DATA);if(data==null){stopSelf();return START_NOT_STICKY;}startForeground(42,notification("Pong bot active"));startProjection(resultCode,data);return START_NOT_STICKY;}
 private void startProjection(int resultCode,Intent data){MediaProjectionManager mpm=(MediaProjectionManager)getSystemService(MEDIA_PROJECTION_SERVICE);projection=mpm.getMediaProjection(resultCode,data);android.util.DisplayMetrics dm=getResources().getDisplayMetrics();int w=dm.widthPixels,h=dm.heightPixels,dpi=dm.densityDpi;reader=ImageReader.newInstance(w,h,PixelFormat.RGBA_8888,2);reader.setOnImageAvailableListener(r->processLatest(),handler);display=projection.createVirtualDisplay("InstagramPongBot",w,h,dpi,DisplayManager.VIRTUAL_DISPLAY_FLAG_AUTO_MIRROR,reader.getSurface(),null,handler);}
 private void processLatest(){Image image=reader.acquireLatestImage();if(image==null)return;try{Image.Plane p=image.getPlanes()[0];ByteBuffer buf=p.getBuffer();int w=image.getWidth(),h=image.getHeight(),pixelStride=p.getPixelStride(),rowStride=p.getRowStride(),rowPadding=rowStride-pixelStride*w;Bitmap bmp=Bitmap.createBitmap(w+rowPadding/pixelStride,h,Bitmap.Config.ARGB_8888);buf.rewind();bmp.copyPixelsFromBuffer(buf);if(bmp.getWidth()!=w)bmp=Bitmap.createBitmap(bmp,0,0,w,h);update(bmp);bmp.recycle();}catch(Throwable t){BotController.status("Capture error: "+t.getClass().getSimpleName());}finally{image.close();}}
 private void update(Bitmap b){long ts=SystemClock.uptimeMillis();PongDetector.Observation o=detector.detect(b);if(o.ballFound){if(lastTs>0){float dt=Math.max(.008f,Math.min(.10f,(ts-lastTs)/1000f));vx=(o.ballX-lastBallX)/dt;vy=(o.ballY-lastBallY)/dt;}lastBallX=o.ballX;lastBallY=o.ballY;lastTs=ts;}if(o.ballFound&&o.paddleFound&&vy>20f){float target=predictX(o.ballX,o.ballY,vx,vy,o.paddleY,b.getWidth(),o.ballRadius);target=Math.max(30,Math.min(b.getWidth()-30,target));if(currentTouchX<0)currentTouchX=o.paddleX;if(BotController.shouldMove(target,b.getWidth())){PongAccessibilityService svc=PongAccessibilityService.instance;if(svc!=null){float from=currentTouchX;currentTouchX=target;svc.movePaddle(from,target,o.paddleY,90);}}BotController.status(String.format(java.util.Locale.US,"Ball x=%.0f y=%.0f v=(%.0f,%.0f)\nPaddle x=%.0f target=%.0f",o.ballX,o.ballY,vx,vy,o.paddleX,target));}else if(o.ballFound)BotController.status(String.format(java.util.Locale.US,"Tracking ball: x=%.0f y=%.0f\nWaiting for downward trajectory...",o.ballX,o.ballY));}
 private float predictX(float x,float y,float vx,float vy,float paddleY,float width,float radius){float t=(paddleY-y-radius)/Math.max(1f,vy);t=Math.max(.02f,Math.min(1.5f,t));float predicted=x+vx*t,left=12+radius,right=width-12-radius,span=right-left;if(span<=1)return width/2f;float z=predicted-left,period=span*2f;z=((z%period)+period)%period;if(z>span)z=period-z;return left+z;}
 private Notification notification(String text){PendingIntent pi=PendingIntent.getActivity(this,0,new Intent(this,MainActivity.class),PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);return new Notification.Builder(this,CHANNEL).setContentTitle("Instagram Pong Bot").setContentText(text).setSmallIcon(android.R.drawable.ic_media_play).setContentIntent(pi).setOngoing(true).build();}
 private void createChannel(){NotificationManager nm=(NotificationManager)getSystemService(Context.NOTIFICATION_SERVICE);nm.createNotificationChannel(new NotificationChannel(CHANNEL,"Pong Bot",NotificationManager.IMPORTANCE_LOW));}
 @Override public void onDestroy(){if(display!=null)display.release();if(reader!=null)reader.close();if(projection!=null)projection.stop();if(thread!=null)thread.quitSafely();super.onDestroy();}
 @Override public IBinder onBind(Intent intent){return null;}
}
